spring:
  application:
    name: zuul
    
server:
  port: 8080
  
zuul:
  routes:
    catalog: 
      path: /catalogs/**
      service-id: catalog
      stripPrefix: false
    customer: 
      path: /customers/**
      service-id: customer
      
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
   service-url:
     defalutZone: http://localhost:8761/eureka         
            
